apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: api-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: trigger-binding-ratings-api
  template:
    ref: trigger-template-ratings-api
